# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  # ubuntu/trusty64 Official Ubuntu Server 14.04 LTS (Trusty Tahr) builds
  config.vm.box = "ubuntu/trusty64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  #config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine.

  # Forward local host port 8080 to zeppelin port 8080
  # Forward local host port 4040 to spark UI port 4040
  # Forward local host port 4000 to jekyll documentation port 4000
  # comment out the following lines to use a fixed IP
  #config.vm.network "forwarded_port", guest: 5050, host: 5050
  #config.vm.network "forwarded_port", guest: 5051, host: 5051
  #config.vm.network "forwarded_port", guest: 5051, host: 5051


  # Uncomment to create a private network, which allows access to the machine
  # using a specific IP.  Port forwarding not required in this case.
  # Select an address range based on a free block available
  # in your network environment.  192.168.x.x is an example
  config.vm.network "private_network", ip: "192.168.51.52"

  # Set the hostname.  Comment this out if you don't want the hostname managed by the VM
  config.vm.hostname = "mesos"

  # Modify the number of CPUs and memory used by the VM
  # by adjusting
  #   --memory
  # and uncommenting and/or updating
  #   --cpus

  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "2048"]
     #vb.customize ["modifyvm", :id, "--cpus", "2"]
     vb.name = "zeppelinvm"
  end

  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "ansible-roles.yml"
  end

  config.vm.provision "shell", path: "show-instructions.sh", run: "always"

end
